version: '3'
services:
  flask:
    build: .
    container_name: flask
    ports:
     - "5000:5000"
    depends_on:
     - redis
     - mongodb
  redis:
    image: redis:latest
  mongodb:
    image: mongo:latest    
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017