version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - redis
     - db
    links:
      - redis
      - db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: mongo:latest
    command: mongod
    
    environment:
     - MONGO_INITDB_ROOT_USERNAME:admin
     - MONGO_INITDB_ROOT_PASSWORD:admin
     - MONGO_INITDB_DATABASE:matav
    ports:
      - 27017:27017